import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';

const API_BASE_URL = 'http://localhost:5000/api';
const SERVER_URL = 'http://localhost:5000';

// ── translations ──────────────────────────────────────────────────────────────
// Only 'en' and 'hi' are supported. All strings sourced from the DR-SUGAR
// medical context; no fake or machine-generated translations.
const T = {
  en: {
    pageSubtitle: 'Patient Screening Summary',
    patientLabel: 'Patient',
    screeningLabel: 'Screening',
    agePrefix: (age: string) => `Age ${age}`,
    male: 'Male',
    female: 'Female',
    retinalScan: 'Your Retinal Scan',
    screeningResult: 'Screening Result',
    gradePrefix: 'Grade',
    modelConfidence: 'Model confidence:',
    drLabels: ['No DR', 'Mild DR', 'Moderate DR', 'Severe DR', 'Proliferative DR'],
    recSpecialist: 'Recommendation: See a Specialist',
    recSpecialistBody:
      'Based on these results, we recommend scheduling a follow-up appointment with an ophthalmologist for a comprehensive eye examination as soon as possible.',
    recRoutine: 'Recommendation: Routine Care',
    recRoutineBody:
      'Your preliminary results do not indicate referable diabetic retinopathy at this time. Continue with regular annual eye check-ups and diabetes management.',
    whatMeans: 'What Do These Results Mean?',
    explainerIntro:
      'Diabetic retinopathy (DR) is damage to the blood vessels in the retina caused by diabetes. This AI screening system examined your retinal photograph and assigned a severity grade from 0 (no DR) to 4 (severe, proliferative DR).',
    referableGradeNote: (grade: number, label: string) =>
      `A Grade ${grade} result (${label}) suggests changes in your retina that may benefit from specialist review.`,
    notConfirmedDiagnosis: 'This does not mean you have a confirmed diagnosis.',
    qualifiedOphth: 'Only a qualified ophthalmologist can provide a formal assessment.',
    nonReferableGradeNote: (grade: number, label: string) =>
      `A Grade ${grade} result (${label}) suggests no significant retinal changes were detected at this time. Regular monitoring is still important for people with diabetes.`,
    nextStep: 'Next step:',
    nextStepReferable:
      'Please contact an eye specialist or your diabetes care team to arrange a full retinal examination.',
    nextStepRoutine:
      'Continue your regular diabetes management and schedule your next routine eye screening as advised by your doctor.',
    importantNotice: 'Important Notice',
    disclaimer:
      'This is an automated preliminary screening report generated by an AI research prototype (DR-SUGAR). It does',
    disclaimerNot: 'not',
    disclaimerRest:
      'constitute a clinical diagnosis and should not replace professional medical advice. Only a qualified medical professional can formally diagnose and treat diabetic retinopathy.',
    printReport: 'Print Report',
    newScreening: 'New Screening',
    allReports: 'All Reports',
  },
  hi: {
    pageSubtitle: 'रोगी जांच सारांश',
    patientLabel: 'रोगी',
    screeningLabel: 'जांच',
    agePrefix: (age: string) => `आयु ${age}`,
    male: 'पुरुष',
    female: 'महिला',
    retinalScan: 'आपका रेटिना स्कैन',
    screeningResult: 'जांच परिणाम',
    gradePrefix: 'ग्रेड',
    modelConfidence: 'मॉडल विश्वास:',
    drLabels: [
      'DR नहीं',
      'हल्का DR',
      'मध्यम DR',
      'गंभीर DR',
      'प्रसारात्मक DR',
    ],
    recSpecialist: 'सिफारिश: विशेषज्ञ से मिलें',
    recSpecialistBody:
      'इन परिणामों के आधार पर, हम जल्द से जल्द एक नेत्र रोग विशेषज्ञ (ऑप्थेल्मोलॉजिस्ट) से व्यापक आंख की जांच के लिए अपॉइंटमेंट लेने की सलाह देते हैं।',
    recRoutine: 'सिफारिश: नियमित देखभाल',
    recRoutineBody:
      'आपके प्रारंभिक परिणाम इस समय मधुमेह संबंधी रेटिनोपैथी का संकेत नहीं देते। नियमित वार्षिक आंख की जांच और मधुमेह प्रबंधन जारी रखें।',
    whatMeans: 'ये परिणाम क्या दर्शाते हैं?',
    explainerIntro:
      'मधुमेह संबंधी रेटिनोपैथी (DR) मधुमेह के कारण रेटिना की रक्त वाहिकाओं को होने वाली क्षति है। इस AI जांच प्रणाली ने आपकी रेटिना की तस्वीर की जांच की और गंभीरता ग्रेड 0 (DR नहीं) से 4 (गंभीर, प्रसारात्मक DR) तक निर्धारित किया।',
    referableGradeNote: (grade: number, label: string) =>
      `ग्रेड ${grade} परिणाम (${label}) आपके रेटिना में ऐसे बदलाव दर्शाता है जिनके लिए विशेषज्ञ समीक्षा आवश्यक हो सकती है।`,
    notConfirmedDiagnosis: 'इसका अर्थ यह नहीं है कि आपको पक्का निदान हो गया है।',
    qualifiedOphth: 'केवल एक योग्य नेत्र रोग विशेषज्ञ ही औपचारिक मूल्यांकन कर सकते हैं।',
    nonReferableGradeNote: (grade: number, label: string) =>
      `ग्रेड ${grade} परिणाम (${label}) यह दर्शाता है कि इस समय कोई महत्वपूर्ण रेटिना परिवर्तन नहीं पाया गया। मधुमेह से पीड़ित लोगों के लिए नियमित निगरानी अभी भी महत्वपूर्ण है।`,
    nextStep: 'अगला कदम:',
    nextStepReferable:
      'कृपया एक नेत्र विशेषज्ञ या अपनी मधुमेह देखभाल टीम से संपर्क करें और पूर्ण रेटिना जांच की व्यवस्था करें।',
    nextStepRoutine:
      'अपने नियमित मधुमेह प्रबंधन को जारी रखें और अपने डॉक्टर की सलाह के अनुसार अगली नियमित आंख की जांच कराएं।',
    importantNotice: 'महत्वपूर्ण सूचना',
    disclaimer:
      'यह एक AI शोध प्रोटोटाइप (DR-SUGAR) द्वारा स्वचालित रूप से तैयार की गई प्रारंभिक जांच रिपोर्ट है। यह',
    disclaimerNot: 'नहीं',
    disclaimerRest:
      'एक नैदानिक निदान है और इसे पेशेवर चिकित्सा सलाह का विकल्प नहीं माना जाना चाहिए। केवल एक योग्य चिकित्सक ही मधुमेह संबंधी रेटिनोपैथी का औपचारिक निदान और उपचार कर सकते हैं।',
    printReport: 'रिपोर्ट प्रिंट करें',
    newScreening: 'नई जांच',
    allReports: 'सभी रिपोर्ट',
  },
} as const;

type Lang = keyof typeof T;

const PatientReport = () => {
  const { id } = useParams();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetch(`${API_BASE_URL}/screening/${id}`)
      .then(res => res.json())
      .then(resData => {
        if (resData.success) {
          setData(resData.data);
        } else {
          setError('Screening record not found.');
        }
        setLoading(false);
      })
      .catch(() => {
        setError('Failed to connect to server.');
        setLoading(false);
      });
  }, [id]);

  if (loading) return (
    <div className="p-24 text-center text-gray-400 animate-pulse">Loading Report...</div>
  );
  if (error || !data) return (
    <div className="p-24 text-center text-red-600 font-bold">{error || 'Report not found.'}</div>
  );

  const lang: Lang = data.preferred_language === 'hi' ? 'hi' : 'en';
  const t = T[lang];

  const isReferable = Boolean(data.referable_dr);
  const grade = data.result_grade ?? 0;
  const drLabel = t.drLabels[grade] ?? t.drLabels[0];

  // Date locale: use hi-IN for Hindi so month names are in Hindi
  const dateLocale = lang === 'hi' ? 'hi-IN' : 'en-GB';

  return (
    <div className="max-w-3xl mx-auto py-16 px-8 bg-[#fafafa] text-[#111] min-h-screen" lang={lang}>
      <style>{`
        @media print {
          .print\\:hidden { display: none !important; }
          body { background: white !important; color: black !important; }
        }
      `}</style>

      {/* Header */}
      <div className="text-center border-b border-[#ddd] pb-8 mb-12">
        <h1 className="text-3xl font-light tracking-widest uppercase mb-1">DR-SUGAR</h1>
        <p className="text-sm text-gray-400 uppercase tracking-widest">{t.pageSubtitle}</p>
      </div>

      {/* Patient details block */}
      <div className="grid grid-cols-2 gap-8 mb-10 text-sm">
        <div>
          <p className="text-xs uppercase tracking-widest text-gray-400 font-bold mb-3">{t.patientLabel}</p>
          <p className="font-semibold text-lg mb-1">{data.patient_name || 'N/A'}</p>
          <p className="text-gray-500">
            {data.patient_age ? t.agePrefix(data.patient_age) : ''}
            {data.patient_age && data.patient_gender ? ', ' : ''}
            {data.patient_gender === 'M' ? t.male : data.patient_gender === 'F' ? t.female : data.patient_gender || ''}
          </p>
        </div>
        <div className="text-right">
          <p className="text-xs uppercase tracking-widest text-gray-400 font-bold mb-3">{t.screeningLabel}</p>
          <p className="text-gray-500 mb-1">ID {data.display_id || data.id}</p>
          <p className="text-gray-500">
            {new Date(data.created_at).toLocaleDateString(dateLocale, {
              day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Asia/Kolkata'
            })}
          </p>
        </div>
      </div>

      {/* Fundus image */}
      {data.image_path && (
        <div className="mb-10 border border-[#eee] overflow-hidden">
          <p className="text-xs font-bold uppercase tracking-widest text-gray-400 px-4 py-3 border-b border-[#eee]">
            {t.retinalScan}
          </p>
          <img
            src={`${SERVER_URL}/uploads/${data.image_path}`}
            alt="Retinal fundus image"
            className="w-full object-contain max-h-56"
          />
        </div>
      )}

      {/* Result card */}
      <div className="bg-white border border-[#eee] p-8 shadow-sm mb-10">
        <h2 className="text-xl font-light mb-6 uppercase tracking-widest border-b border-[#eee] pb-4">
          {t.screeningResult}
        </h2>

        <div className="flex flex-col md:flex-row items-start gap-8">
          <div className="flex-1">
            <p className="text-5xl font-light text-black mb-2">{t.gradePrefix} {grade}</p>
            <p className="text-base font-semibold text-gray-500 uppercase tracking-widest mb-4">
              {drLabel}
            </p>
            <p className="text-sm text-gray-500">
              {t.modelConfidence}{' '}
              <span className="font-semibold text-black">
                {data.confidence != null ? (data.confidence * 100).toFixed(1) : 'N/A'}%
              </span>
            </p>
          </div>

          <div className="flex-1">
            {isReferable ? (
              <div className="bg-red-50 text-red-800 p-6 border border-red-200 text-sm leading-relaxed">
                <strong className="block mb-2 uppercase tracking-widest text-xs">{t.recSpecialist}</strong>
                {t.recSpecialistBody}
              </div>
            ) : (
              <div className="bg-green-50 text-green-800 p-6 border border-green-200 text-sm leading-relaxed">
                <strong className="block mb-2 uppercase tracking-widest text-xs">{t.recRoutine}</strong>
                {t.recRoutineBody}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* What this means */}
      <div className="bg-white border border-[#eee] p-8 shadow-sm mb-10">
        <h2 className="text-lg font-light mb-4 uppercase tracking-widest border-b border-[#eee] pb-3">
          {t.whatMeans}
        </h2>
        <div className="text-sm text-gray-600 leading-relaxed space-y-3">
          <p>{t.explainerIntro}</p>
          {isReferable ? (
            <p>
              {t.referableGradeNote(grade, drLabel)}{' '}
              <strong>{t.notConfirmedDiagnosis}</strong>{' '}
              {t.qualifiedOphth}
            </p>
          ) : (
            <p>{t.nonReferableGradeNote(grade, drLabel)}</p>
          )}
          <p>
            <strong>{t.nextStep}</strong>{' '}
            {isReferable ? t.nextStepReferable : t.nextStepRoutine}
          </p>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="text-xs text-gray-400 leading-relaxed border-t border-[#ddd] pt-8 mb-8">
        <strong className="text-gray-600 uppercase tracking-widest block mb-2">{t.importantNotice}</strong>
        {t.disclaimer} <strong>{t.disclaimerNot}</strong> {t.disclaimerRest}
      </div>

      <div className="flex justify-center gap-6 print:hidden">
        <button
          onClick={() => window.print()}
          className="bg-black text-white px-8 py-3 text-sm uppercase tracking-widest hover:opacity-90"
        >
          {t.printReport}
        </button>
        <Link
          to="/screening"
          className="border border-black px-8 py-3 text-sm uppercase tracking-widest hover:bg-black hover:text-white transition-colors"
        >
          {t.newScreening}
        </Link>
        <Link
          to="/reports"
          className="border border-[#ddd] px-8 py-3 text-sm uppercase tracking-widest hover:bg-gray-100 transition-colors"
        >
          {t.allReports}
        </Link>
      </div>
    </div>
  );
};

export default PatientReport;
